### ISSUE TITLE
Build failed due to exit code 65:

### ISSUE THREAD

**Issue by Tonyabott** [ringcentral/ringcentral-swift#10]
on update carthage for my iOS project:

*** Fetching ringcentral-swift
*** Fetching CryptoSwift
*** Fetching ObjectMapper
*** Fetching objective-c
*** Fetching Alamofire
*** Checking out objective-c at "v4.7.5"
*** Checking out Alamofire at "4.6.0"
*** Checking out ObjectMapper at "3.1.0"
*** Checking out ringcentral-swift at "0.7.1"
*** Downloading CryptoSwift.framework binary at "0.8.0"
*** Skipped installing CryptoSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out CryptoSwift at "0.8.0"
*** xcodebuild output can be found in /var/folders/zw/6q26sn9n7gzggwm6rm_fx_2h0000gp/T/carthage-xcodebuild.KkNIZh.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "CryptoSwift" in CryptoSwift.xcworkspace
*** Building scheme "Framework (iOS)" in PubNub.xcworkspace
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
*** Building scheme "RingCentral_iOS" in RingCentral.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/XXXXXXXXX/Downloads/RingcentralSwiftSdkDemo/RingcentralSwiftSdkDemo/Carthage/Checkouts/ringcentral-swift/RingCentral.xcodeproj -scheme RingCentral_iOS -configuration Release -derivedDataPath /Users/XXXXXXXXX/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/ringcentral-swift/0.7.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/zw/6q26sn9n7gzggwm6rm_fx_2h0000gp/T/ringcentral-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/XXXXXXXXX/Downloads/RingcentralSwiftSdkDemo/RingcentralSwiftSdkDemo/Carthage/Checkouts/ringcentral-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/zw/6q26sn9n7gzggwm6rm_fx_2h0000gp/T/carthage-xcodebuild.KkNIZh.log

**Comment by maxtang2013** [comment]
I got the same error with Xcode 9, swift 4

**Comment by tylerlong** [comment]
I cannot reproduce the issue. The project compiles with not problem when targeting iOS:

```
➜  ringcentral-swift git:(master) carthage update --platform iOS
*** Fetching CryptoSwift
*** Fetching ObjectMapper
*** Fetching objective-c
*** Fetching Alamofire
*** Checking out Alamofire at "4.7.0"
*** Downloading CryptoSwift.framework binary at "0.8.3"
*** Checking out objective-c at "v4.7.7"
*** Checking out ObjectMapper at "3.1.0"
*** xcodebuild output can be found in /var/folders/9y/gtjy0bps60l0bfk2bxvw96bd7sz_7r/T/carthage-xcodebuild.5GTM1L.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Framework (iOS)" in PubNub.xcworkspace
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
➜  ringcentral-swift git:(master)
```

Could you please try the latest version and let me know whether it works for you?

If it doesn't, please reopen this issue and give me a link to a demo project. Thank you very much!

**Comment by ustechverx** [comment]
Not working for me

carthage update --platform iOS
*** Fetching ringcentral-swift
*** Fetching CryptoSwift
*** Fetching objective-c
*** Fetching Alamofire
*** Fetching ObjectMapper
*** Checking out ObjectMapper at "3.4.2"
*** Checking out Alamofire at "4.8.1"
*** Checking out ringcentral-swift at "1.0.1"
*** Checking out CryptoSwift at "0.14.0"
*** Checking out objective-c at "v4.8.5"
*** xcodebuild output can be found in /var/folders/49/ckkpnf9n6lgbfsfp407twf840000gn/T/carthage-xcodebuild.gTqjHT.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "CryptoSwift" in CryptoSwift.xcworkspace
*** Building scheme "Framework (iOS)" in PubNub.xcworkspace
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
*** Building scheme "RingCentral_iOS" in RingCentral.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/xxxxxxxxx/Downloads/MyFax\ /Carthage/Checkouts/ringcentral-swift/RingCentral.xcodeproj -scheme RingCentral_iOS -configuration Release -derivedDataPath /Users/xxxxxxxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/ringcentral-swift/1.0.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/49/ckkpnf9n6lgbfsfp407twf840000gn/T/ringcentral-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xxxxxxxxx/Downloads/MyFax /Carthage/Checkouts/ringcentral-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/49/ckkpnf9n6lgbfsfp407twf840000gn/T/carthage-xcodebuild.gTqjHT.log
