### ISSUE TITLE
Fax send is not working

### ISSUE THREAD

**Issue by sweetcodestar** [ringcentral/ringcentral-swift#11]
Hi @tylerlong.

I am working Xcode 9.3, iOS 11.3 and I am going to send the Fax in the mobile app using RingCentral.
Following code does not work.
        let parameters = FaxPath.PostParameters(to: [CallerInfo(phoneNumber: phone)])
        var attachments: [Attachment] = []
        for image in images {
            attachments.append(Attachment(fileName: "image.jpg", contentType: "image/jpeg", data: UIImageJPEGRepresentation(image, 1.0)!))
        }
        client.restapi().account().extension().fax().post(parameters: parameters, attachments: attachments) { messageInfo, error in
            if let error = error {
                completion(error as? Error)
            } else {
                print("Fax has sent")
                completion(nil)
            }
        }

The problem is that 
Type 'FaxPath' has no member 'PostParameters'

Can you please let me know what is the problem?
Regards.
Hua.

**Comment by tylerlong** [comment]
Please check the sample code here: https://github.com/ringcentral/ringcentral-swift/blob/master/Tests/FaxTest.swift#L8

`let parameters: Parameters = ["to": [["phoneNumber": phone]]]` should work.
