### ISSUE TITLE
carthage update --platform iOS

### ISSUE THREAD

**Issue by BRLOKESH** [ringcentral/ringcentral-swift#13]
carthage update --platform iOS . OR   carthage update --platform iphoneos .  

*** Checking out Alamofire at "4.7.2"
*** Checking out objective-c at "v4.8.1"
*** Checking out ringcentral-swift at "0.7.3"
*** Checking out ObjectMapper at "3.3.0"
*** Checking out CryptoSwift at "0.10.0"

RingCentral_iOS issue occur  when Build.

*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "CryptoSwift" in CryptoSwift.xcworkspace
*** Building scheme "Framework (iOS)" in PubNub.xcworkspace
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
*** Building scheme "RingCentral_iOS" in RingCentral.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/apple/Desktop/Lokesh\ Kumawat/WCS\ TEST/Woundcare\ copy/Carthage/Checkouts/ringcentral-swift/RingCentral.xcodeproj -scheme RingCentral_iOS -configuration Release -derivedDataPath /Users/apple/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/ringcentral-swift/0.7.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/c_/nkxb3yr92ld6nq3wdjcgkggr0000gn/T/ringcentral-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/apple/Desktop/Lokesh Kumawat/WCS TEST/Woundcare copy/Carthage/Checkouts/ringcentral-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/c_/nkxb3yr92ld6nq3wdjcgkggr0000gn/T/carthage-xcodebuild.fOTYlH.log

**Comment by tylerlong** [comment]
It seems that `CryptoSwift` has some breaking change since 0.10.0, I am updating the code.

**Comment by tylerlong** [comment]
Fixed, please check latest code.

**Comment by ustechverx** [comment]
Not working for me

carthage update --platform iOS
*** Fetching ringcentral-swift
*** Fetching CryptoSwift
*** Fetching objective-c
*** Fetching Alamofire
*** Fetching ObjectMapper
*** Checking out ObjectMapper at "3.4.2"
*** Checking out Alamofire at "4.8.1"
*** Checking out ringcentral-swift at "1.0.1"
*** Checking out CryptoSwift at "0.14.0"
*** Checking out objective-c at "v4.8.5"
*** xcodebuild output can be found in /var/folders/49/ckkpnf9n6lgbfsfp407twf840000gn/T/carthage-xcodebuild.gTqjHT.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "CryptoSwift" in CryptoSwift.xcworkspace
*** Building scheme "Framework (iOS)" in PubNub.xcworkspace
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
*** Building scheme "RingCentral_iOS" in RingCentral.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/xxxxxxxxx/Downloads/MyFax\ /Carthage/Checkouts/ringcentral-swift/RingCentral.xcodeproj -scheme RingCentral_iOS -configuration Release -derivedDataPath /Users/xxxxxxxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/ringcentral-swift/1.0.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/49/ckkpnf9n6lgbfsfp407twf840000gn/T/ringcentral-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xxxxxxxxx/Downloads/MyFax /Carthage/Checkouts/ringcentral-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/49/ckkpnf9n6lgbfsfp407twf840000gn/T/carthage-xcodebuild.gTqjHT.log
