### ISSUE TITLE
Swift 4 issue BlockMode

### ISSUE THREAD

**Issue by BRLOKESH** [ringcentral/ringcentral-swift#14]
Type 'BlockMode' has no member 'ECB'

SubscriptionService.swift 

public func client(_ client: PubNub, didReceiveMessage message: PNMessageResult) {
        let base64Message = message.data.message as! String
        let encrypted = Data(base64Encoded: base64Message)!.bytes
        let key = Data(base64Encoded: subscriptionInfo!.deliveryMode!.encryptionKey!)!.bytes

        let decrypted = try! AES(key: key, blockMode: .ECB, padding: .pkcs7).decrypt(encrypted)

        let json = String(bytes: decrypted, encoding: String.Encoding.utf8)!
        for listener in listeners {
            let notification = Notification(json: json)!
            listener(notification)
        }
    }

**Comment by tylerlong** [comment]
It seems that `CryptoSwift` has some breaking change since 0.10.0, I am updating the code.

**Comment by tylerlong** [comment]
Fixed, please check latest code.
