### ISSUE TITLE
Add support for Swift 4.0 / Xcode 9.0+

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-swift#8]
Swift 4.0 is included with Xcode 9.0 and is not backward compatible with Swift 3.0.

**Comment by tylerlong** [comment]
https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support

CryptoSwift has requirements for the language versions:

```
Swift versions support

Swift 1.2: branch swift12 version <= 0.0.13
Swift 2.1: branch swift21 version <= 0.2.3
Swift 2.2, 2.3: branch swift2 version <= 0.5.2
Swift 3.1, branch swift3 version <= 0.6.9
Swift 3.2, branch swift32 version = 0.7.0
Swift 4.0, branch master version >= 0.7.1
```

**Comment by tylerlong** [comment]
We are already running the latest Xcode and Swift. I forgot to close this issue.
